name: jarvis-backend
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "5001:5001"
    links:
      - influxdb
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - .:/app
    restart: always
    environment:
      DB_HOST: influxdb
      DB_PORT: 8086
      DB_BUCKET: jarvis
      DB_ORG: umsats
      DB_USER: admin
      DB_PASS: adminPassword
      DB_TOKEN: umsatsAdminToken
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminPassword
      - DOCKER_INFLUXDB_INIT_ORG=umsats
      - DOCKER_INFLUXDB_INIT_BUCKET=jarvis
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=umsatsAdminToken
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 12

volumes:
    influxdb-storage: