tables: # for read the data frame file
  - name: temp # need to match the field name in .env and influx table
    columns:
      - timestamp
      - well_num
      - temperature

  - name: lumin
    columns:
      - timestamp
      - well_num
      - luminosity

  - name: angvel
    columns:
      - variant
      - timestamp
      - X
      - Y
      - Z
    
  - name: magfield
    columns:
      - variant
      - timestamp
      - LSB
      - X
      - Y
      - Z