name: Backend Build

on:
  push:
    branches: [ "main", "dev", "feat/cicd"] # for testing
  pull_request: 
    branches: [ "main", "dev", "feat/cicd"] # for testing

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: move into server directory
        run: cd server
      
      - name: Set up environment variables
        run: |
          echo "DB_HOST=influxdb" >> $GITHUB_ENV
          echo "DB_PORT=8086" >> $GITHUB_ENV
          echo "DB_BUCKET=jarvis" >> $GITHUB_ENV
          echo "DB_ORG=umsats" >> $GITHUB_ENV
          echo "DB_USER=admin" >> $GITHUB_ENV
          echo "DB_PASS=adminPassword" >> $GITHUB_ENV
          echo "DB_TOKEN=umsatsAdminToken" >> $GITHUB_ENV

      - name: Build and test
        run: |
          npm install
          npm run build --if-present
          npm run test
